name: grid_guiding_3dgs
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - plyfile
  - python=3.8.19
  - pip=22.3.1
  - pytorch=2.4.1
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - tqdm
  - matplotlib
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim
    - opencv-python
    - joblib
